default_install_hook_types:
  - pre-commit
  - commit-msg

default_stages: [pre-commit, pre-push]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.18
    hooks:
      - id: ruff-format
      - id: ruff-check
        name: ruff-check

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-docstring-first
        exclude: ^interlock/version\.py$
      - id: check-ast
      - id: check-toml
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: detect-private-key
      - id: no-commit-to-branch
        args: [ --branch, main ]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy --num-workers 2
        language: system
        types: [python]
        pass_filenames: false
        args: [--config-file=./pyproject.toml]

      - id: pyright
        name: pyright
        entry: uv run pyright
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.38
    hooks:
      - id: pymarkdown
        name: pymarkdown
        files: \.md$
        pass_filenames: true
        exclude: (CHANGELOG\.md|^\.github/)

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
